### ISSUE TITLE
Modifying position of Hypothes.is via CSS?

### ISSUE THREAD

**Issue by jasonwhat** [hypothesis/developers.hypothes.is#2]
I'm testing Hypothes.is on a Ghost blog and I need to move the frame down as it is competing with my navigation menu.  Any tips on how I could do this and what CSS I need. I tried to inspect, but couldn't get it to work.

Apologies if this is the wrong place to ask, I'm not sure where I should.

**Comment by segdeha** [comment]
Archiving repo. See https://web.hypothes.is/developers/ for info on how to get questions like this one answered.
