### ISSUE TITLE
Yaml file out of date

### ISSUE THREAD

**Issue by rektide** [hypothesis/developers.hypothes.is#4]
The current [hypothesis.yml](https://github.com/hypothesis/developers.hypothes.is/blob/gh-pages/_data/hypothesis.yml) file includes endpoints which (very sadly!) appear to no longer exist- [latest annotations](https://github.com/hypothesis/developers.hypothes.is/blob/gh-pages/_data/hypothesis.yml#L98-L107). This was my go to, and I was happy to see it in my Swagger/OpenAPI editor, but I was getting failures trying to hit it. Looking at the published documentation, I found there was no corresponding endpoint.

It would be great to have the yml files be up to date.

**Comment by robertknight** [comment]
Hello - This repository is no longer maintained. The current API documentation for the Hypothesis service can be found at https://h.readthedocs.io/en/latest/api/
